# Generated by Django 5.2.11 on 2026-03-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=220)),
                ('speaker', models.CharField(blank=True, max_length=220)),
                ('format', models.CharField(choices=[('talk', 'Talk / Лекция'), ('workshop', 'Workshop / Мастер-класс'), ('show', 'Show / Перформанс'), ('expo', 'Expo / Выставка')], default='talk', max_length=20)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
    ]
